### ISSUE TITLE
model-loader-huggingface: Doesn't work with 

### ISSUE THREAD

**Issue by samos123** [substratusai/images#30]
Steps to reproduce:
```
kubectl apply -f - << EOF
apiVersion: substratus.ai/v1
kind: Model
metadata:
  name: openorca-platypus2-13b
spec:
  image: substratusai/model-loader-huggingface
  params:
    name: Open-Orca/OpenOrca-Platypus2-13B
EOF
```

Error seen:
```
File /usr/lib/python3.10/urllib/request.py:251, in urlretrieve(url, filename, reporthook, data)
    249 # Handle temporary file setup.
    250 if filename:
--> 251     tfp = open(filename, 'wb')
    252 else:
    253     tfp = tempfile.NamedTemporaryFile(delete=False)

FileNotFoundError: [Errno 2] No such file or directory: '/content/model/Images/OrcaPlatypus13BAGIEval.webp'
```
